name: "Luffy Build"

on:
  workflow_dispatch:  # 启用手动触发

jobs:
  build:
    runs-on: [self-hosted,Luffy-Windows]
     #[self-hosted,Luffy-Windows]
    steps:
      - uses: actions/checkout@v4
      - name: Generate table
        uses: parasoft/parasoft-coverage-action@1.0.1
        with:             
            report: 'D:\Sonarqube\sonar-integration-test\parasoft-findings-sonar-integration-test\projects\CppProjectTemplate\report\std\coverage\coverage.xml'
            parasoftToolOrJavaRootPath: 'C:\Program Files\Java\zulu-21.50.19'
